# Generated by Django 4.2.4 on 2023-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_department_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, choices=[('Sofia', 'Sofia'), ('Burgas', 'Burgas'), ('Plovdiv', 'Plovdiv'), ('Varna', 'Varna')], max_length=20, null=True),
        ),
    ]
